# i18n/en.sh - English

MSG_HELLO="Hi! I'm Archy, tell me what you want and I'll install it"
MSG_CHOOSE="Choose an option: "
MSG_INVALID="invalid option"
MSG_BACK="back"
MSG_EXIT="exit"
MSG_SCRIPT_NOT_FOUND="script not found: "
MSG_PRESS_ENTER="press enter to continue..."
MSG_PRESS_ENTER_START="press enter to start..."
MSG_INSTALL_DONE="installation complete"
MSG_REBOOT="reboot now? [y/N]: "

MSG_MENU_DEFAULT_TITLE="Full installation"
MSG_MENU_DEFAULT_1="default installation end-4 dotfiles"
MSG_MENU_DEFAULT_2="default installation imperative-dots"
MSG_MENU_DEFAULT_3="default installation HyDE"

MSG_MENU_CUSTOM_TITLE="Installations"
MSG_MENU_CUSTOM_1="desktop environment"
MSG_MENU_CUSTOM_2="programs"

MSG_MENU_ENTORNO_TITLE="Desktop environment"
MSG_MENU_ENTORNO_1="end-4 dotfiles"
MSG_MENU_ENTORNO_2="imperative-dots"
MSG_MENU_ENTORNO_3="HyDE"
MSG_MENU_ENTORNO_4="sddm theme (silentsddm)"

MSG_MENU_PROGRAMS_TITLE="Programs"
MSG_MENU_PROGRAMS_1="browser"
MSG_MENU_PROGRAMS_2="code editor"
MSG_MENU_PROGRAMS_3="game launcher"
MSG_MENU_PROGRAMS_4="games"
MSG_MENU_PROGRAMS_5="utilities"
MSG_MENU_PROGRAMS_6="communication"

MSG_MENU_BROWSER_TITLE="Browser"
MSG_MENU_EDITOR_TITLE="Code editor"
MSG_MENU_LAUNCHER_TITLE="Game launcher"

MSG_CHOOSE_BROWSER="Choose your browser:"
MSG_CHOOSE_EDITOR="Choose your code editor:"
MSG_CHOOSE_LAUNCHER="Choose your game launcher:"
MSG_NONE="none"
MSG_BOTH="both"

MSG_SUMMARY_TITLE="INSTALLATION SUMMARY:"
MSG_SUMMARY_DOTFILES="- Dotfiles: "
MSG_SUMMARY_BROWSER="- Browser: "
MSG_SUMMARY_EDITOR="- Editor: "
MSG_SUMMARY_LAUNCHER="- Launcher: "

MSG_MENU_MAIN_1="full installation"
MSG_MENU_MAIN_2="installations"
MSG_MENU_MAIN_3="uninstall programs"
MSG_MENU_MAIN_4="settings"
MSG_MENU_MAIN_5="exit"
MSG_MENU_MAIN_6="advanced tools"

MSG_MENU_SETTINGS_TITLE="Settings"
MSG_MENU_SETTINGS_1="change language"
MSG_MENU_SETTINGS_2="update archy"

MSG_LANG_SELECT="Selecciona tu idioma / Select your language / Choisissez votre langue / Sprache wählen:"
MSG_LANG_1="1. Español"
MSG_LANG_2="2. English"
MSG_LANG_3="3. Français"
MSG_LANG_4="4. Deutsch"
MSG_LANG_SAVED="language saved"

MSG_MENU_UNINSTALL_TITLE="Uninstall programs"
MSG_MENU_GAMES_TITLE="Games"
MSG_MENU_UTILS_TITLE="Utilities"
MSG_MENU_COMM_TITLE="Communication"
MSG_MENU_TOOLS_TITLE="Tools"
MSG_MENU_SECURITY_TITLE="Security"
MSG_MENU_FILES_TITLE="Files"
MSG_MENU_OFFICE_TITLE="Office"

MSG_SISTEMA_TITLE="Advanced tools"
MSG_SISTEMA_FORMAT="format disk"
MSG_SISTEMA_DD="dd (clone/disk image)"
MSG_SISTEMA_SMART="smartctl (disk health)"
MSG_SISTEMA_HTOP="htop (system monitor)"
MSG_SISTEMA_CLEAN="cache cleanup"
MSG_SISTEMA_NET="network info"
MSG_SISTEMA_SYSTEMD="systemd (services)"

MSG_CONFIRM_EXIT="are you sure you want to exit?"
MSG_YES="✅ yes, exit"
MSG_NO="❌ no, go back"
MSG_CONFIRM_UNINSTALL="uninstall"
MSG_YES_UNINSTALL="✅ yes, uninstall"
MSG_NO_CANCEL="❌ no, cancel"
MSG_UPDATING=">>> Updating archy..."
MSG_UPDATED=">>> archy updated"
MSG_GOODBYE="Hope it was useful!"
MSG_MINECRAFT="Minecraft"
MSG_MOD_LAUNCHERS="mod launchers"
