# i18n/es.sh - Español

MSG_HELLO="¡Hola! Soy Archy, dime qué quieres y yo lo instalo"
MSG_CHOOSE="Elige una opcion: "
MSG_INVALID="opcion no valida"
MSG_BACK="volver"
MSG_EXIT="salir"
MSG_SCRIPT_NOT_FOUND="script no encontrado: "
MSG_PRESS_ENTER="pulsa enter para continuar..."
MSG_PRESS_ENTER_START="pulsa enter para comenzar..."
MSG_INSTALL_DONE="instalacion completada"
MSG_REBOOT="reiniciar ahora? [s/N]: "

MSG_MENU_DEFAULT_TITLE="Instalación completa"
MSG_MENU_DEFAULT_1="instalacion predeterminada end-4 dotfiles"
MSG_MENU_DEFAULT_2="instalacion predeterminada imperative-dots"
MSG_MENU_DEFAULT_3="instalacion predeterminada HyDE"

MSG_MENU_CUSTOM_TITLE="Instalaciones"
MSG_MENU_CUSTOM_1="entorno de escritorio"
MSG_MENU_CUSTOM_2="programas"

MSG_MENU_ENTORNO_TITLE="Entorno de escritorio"
MSG_MENU_ENTORNO_1="end-4 dotfiles"
MSG_MENU_ENTORNO_2="imperative-dots"
MSG_MENU_ENTORNO_3="HyDE"
MSG_MENU_ENTORNO_4="tema sddm (silentsddm)"

MSG_MENU_PROGRAMS_TITLE="Programas"
MSG_MENU_PROGRAMS_1="navegador"
MSG_MENU_PROGRAMS_2="editor de codigo"
MSG_MENU_PROGRAMS_3="launcher de juegos"

MSG_MENU_BROWSER_TITLE="Navegador"
MSG_MENU_EDITOR_TITLE="Editor de codigo"
MSG_MENU_LAUNCHER_TITLE="Launcher de juegos"

MSG_CHOOSE_BROWSER="Elige tu navegador:"
MSG_CHOOSE_EDITOR="Elige tu editor de codigo:"
MSG_CHOOSE_LAUNCHER="Elige tu launcher de juegos:"
MSG_NONE="ninguno"
MSG_BOTH="ambos"

MSG_SUMMARY_TITLE="RESUMEN DE INSTALACION:"
MSG_SUMMARY_DOTFILES="- Dotfiles: "
MSG_SUMMARY_BROWSER="- Navegador: "
MSG_SUMMARY_EDITOR="- Editor: "
MSG_SUMMARY_LAUNCHER="- Launcher: "

MSG_MENU_MAIN_1="instalación completa"
MSG_MENU_MAIN_2="instalaciones"
MSG_MENU_MAIN_3="desinstalar programas"
MSG_MENU_MAIN_4="ajustes"
MSG_MENU_MAIN_5="salir"

MSG_MENU_SETTINGS_TITLE="Ajustes"
MSG_MENU_SETTINGS_1="cambiar idioma"

MSG_LANG_SELECT="Selecciona tu idioma / Select your language / Choisissez votre langue / Sprache wählen:"
MSG_LANG_1="1. Español"
MSG_LANG_2="2. English"
MSG_LANG_3="3. Français"
MSG_LANG_4="4. Deutsch"
MSG_LANG_SAVED="idioma guardado"
MSG_MENU_UNINSTALL_TITLE="Desinstalar programas"